### ISSUE TITLE
服务注册出现500错误

### ISSUE THREAD

**Issue by xstarts** [heqingpan/rnacos#1]
![image](https://user-images.githubusercontent.com/16752449/236717463-0fbd88ca-e398-473b-935d-401459db0d03.png)

**Comment by heqingpan** [comment]
这个是查询的配置信息不存在，需要先到控制台加下对应的配置。

**Comment by heqingpan** [comment]
这个日志是预期内的处理。
这里先关掉，如果还有问题，可以增加对应的客户端使用信息再重提。
