### ISSUE TITLE
配置中心导出配置文件为空

### ISSUE THREAD

**Issue by VINO42** [heqingpan/rnacos#12]
新建properties 读取不到 导出也有问题，仓主可以试试

**Comment by VINO42** [comment]
新建一个dataid

**Comment by heqingpan** [comment]
你新建的properties是通过什么方式创建的？是在控制台创建还是通过 api 创建？

我这边试了创建是可以查到数据的。

----

控制台查询配置信息，是按命名空间作隔离的。

要先确认创建的命名空间与控制台查询的命名空间是否一致。

如果不一致，先维护对应的命名空间再切换到对应名命空间查询。

创建命名空间
<img width="1409" alt="image" src="https://github.com/heqingpan/rnacos/assets/1174480/b5644002-364a-40ff-ba31-4b00b669257e">

<img width="1411" alt="image" src="https://github.com/heqingpan/rnacos/assets/1174480/4947b9f8-79e1-48e2-97fe-e9767e26ddc0">

切换命名空间查询：
![Uploading image.png…]()

**Comment by VINO42** [comment]
这个 我知道 等下我录个屏看看，一个问题是新建 一个问题是下载zip

**Comment by VINO42** [comment]
因为之前在本地是从java的nacos上下载导入进去的。没有新建过也没有导出过。

**Comment by VINO42** [comment]
这是下载导出 发现是空的zip文件
![screenshots](https://github.com/heqingpan/rnacos/assets/17560849/22f6768a-6929-4860-a758-a29a4fe1246e)

**Comment by VINO42** [comment]
> 这是下载导出 发现是空的zip文件 ![screenshots](https://user-images.githubusercontent.com/17560849/268431940-22f6768a-6929-4860-a758-a29a4fe1246e.gif) [ ![screenshots](https://user-images.githubusercontent.com/17560849/268431940-22f6768a-6929-4860-a758-a29a4fe1246e.gif) ](https://user-images.githubusercontent.com/17560849/268431940-22f6768a-6929-4860-a758-a29a4fe1246e.gif) [ ](https://user-images.githubusercontent.com/17560849/268431940-22f6768a-6929-4860-a758-a29a4fe1246e.gif)

不是idm下载的问题 我用谷歌自带的浏览器下载也是空的 很奇怪。。。

**Comment by VINO42** [comment]
不是idm下载的问题 我用谷歌自带的浏览器下载也是空的 很奇怪。。。

**Comment by VINO42** [comment]
rnacos的控制台也没有报错。

**Comment by VINO42** [comment]
新建的配置 我重新试了下是我操作问题 这次新建后获取到了。

**Comment by heqingpan** [comment]
那就是下载的问题了。

我看了上面截图，问题已收到。

---

我刚在我本地(mac)试了下下载配置，功能是正常的。
可能是环境问题，我当时之前没有在windows 试过下载。 

如果我在windows环境能复现，我会争取在今天内修复这个问题。

**Comment by heqingpan** [comment]
已确认问题原因和系统无关，是下载的配置链接中的命名空间参数固定写成默认命名空间（空字符串），切换命名空间后点下载，对应的参数也没有变化。

本地的下载链接是：http://127.0.0.1:8848/nacos/v1/console/config/download?dataParam=&groupParam=&tenant=&pageNo=1&pageSize=20  ，把tenant参数更新成对应命名空间后就参下载对应命名空间下的配置。

原因已确认我今天应该能修复这个问题。

**Comment by VINO42** [comment]
没事 不急 我只是在用的过程中发现了这个问题

**Comment by heqingpan** [comment]
问题已修复 。
单机版本：0.2.3  
集群版本：0.3.0 （也支持单机部署）
