### ISSUE TITLE
【界面优化】顶部左侧展示命名空间

### ISSUE THREAD

**Issue by greenhand520** [heqingpan/rnacos#133]
如图所示：
![image](https://github.com/user-attachments/assets/09ef6073-4b16-4a0d-8f6f-a31c6110c795)

**Comment by heqingpan** [comment]
主要是想解决命名空间名称太长展示不全的问题是吧？

左右两边都展示命名空间感觉有点重复，或者可以考虑增加下拉框长度，我看看怎么调整比较合适。

实在不行也可以通过配置控制是否开启左侧也展示。

**Comment by heqingpan** [comment]
尝试后初定调整内容：

1）将命名空间组件宽度增加一些；
2）命名空间组件下拉选择时宽度随内容扩大（没有超过宽度时和之前保持一致）；

如图：
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/9b0b560d-7526-4eca-b192-0424c53f5a90">

本次调整大概本周日晚发布，下周一可用。

**Comment by heqingpan** [comment]
@greenhand520  r-nacos v0.5.22 版本已发布，抽空更新确认下是否已解决你的问题。
