### ISSUE TITLE
java连接rnacos的时候 不用指定username和password就可以直接使用吗

### ISSUE THREAD

**Issue by Xuan0902** [heqingpan/rnacos#168]
这个鉴权只是对控制台鉴权吗
因为nacos开启了鉴权是必须匹配username和password才可以连接到的

**Comment by heqingpan** [comment]
老控制台（默认不开启）的鉴权与接口鉴权是由不同的配置控制（默认不鉴权）。

RNACOS_ENABLE_OPEN_API_AUTH 参数是控制接口鉴权，
RNACOS_ENABLE_NO_AUTH_CONSOLE 这个是控制是否开启无鉴权控制台。

另外接口鉴权开启后，无鉴权控制台不支持开启。

**Comment by Xuan0902** [comment]
开启控制接口鉴权的话 用户名和密码是登录的用户名和密码吗还是有角色的区分 只能是管理员

**Comment by heqingpan** [comment]
鉴权的登录密码就是控制台中的用户密码。

目前接口没有角色校验（后面可能会加上），推荐用开发者角色的用户。

**Comment by Xuan0902** [comment]
了解了 谢谢 rnacos非常好用
