### ISSUE TITLE
大佬，我想参与到开发当中，请问是否可以？

### ISSUE THREAD

**Issue by azusachino** [heqingpan/rnacos#2]
我这边，工作中也是用 Java+Nacos 的，学了 Rust 之后一直不知道干啥。
如果大佬觉得可以的话，可以给我分配几个任务，我在工作以外的时间尽量完成，目前也是在熟悉项目的过程中。
anyway，谢谢。

**Comment by heqingpan** [comment]
可以的，欢迎共建。

我晚点整理一下当前阶段的待办事项，然后你再选个合适自己的开发。

**Comment by heqingpan** [comment]
@azusachino 

## rnacos 后继开发计划


### 一、 对单机功能补全

1. 配置中心
	1. 配置变更支持内容比较确认后再提交。【主要涉及前端页面的开发，本人正在开发中】
	2. 配置数据单机存储从 sqlite 切换到sled。（目前数据库主要用于数据持久化，查询可以都用内存索引。切换成 sled 应该会更快一些）
	3. 调整配置中心的 `ConfigValue`结构，使其支持 beta 配置与 tags 配置（目前只存在正式内容）。
	4. 支持beta发布、订阅（按指定 ip与正式内容区分开），与 nacos 接口功能对齐。
	5. 支持tag发布、订阅（按指定tag与正式内容区分开)，与 nacos 接口功能对齐
	6. 支持查询服务监听列表
2. 注册中心
	1. 重新开启1.x版本用到的 udp 实例变更通知机制
	2. 支持查询服务监听列表
	3. NamingActor支持按ServiceKey hash value 增加分桶，每个分桶的 actor 单据运行在一个独立的线程中，增加单机多核的使用率，提高单机负载量。【可选，支持集群后，单机性能、裁量不是短板】

### 二、支持集群部署

1. 配置中心数据支持raft+sled （优先） 或  mysql 存储 （保险兜底）
2. 注册中心支持集群  (暂定使用类distro协议)
	1. 写路由
	2. 集群间的数据同步
3. 其它
	1. 集群用户认证同步

### 三、 性能基线

1. 构建可复用的压测工具，再功能调整后，压测回归，确认性能变化情况。（目前本人只建一套 http 协议接口压测工具，grpc 压测工具依赖 grpc client 的现在，目前正在开发）
2. 后面通过github action ,在大版本变更后，触发压测工具生成性能基线。


------------
上面是当前阶段的待办事项，你可以选单机优先中的配置相关的开发；
选中后直接开个功能issue用于沟通，开发好后提 PR 即可。

另外目前对共建开发的文档缺失，我晚点会补上这部分内容（先补项目使用的技术栈和工程详细模型图）

**Comment by heqingpan** [comment]
配置中心模型图已加到rnacos book  <https://heqingpan.github.io/rnacos/architecture.html>

**Comment by azusachino** [comment]
tags 这个功能，感觉在工作中基本没用到过，，至于说 beta 配置，就根本没听过了，nacos 里有这个概念吗？
如果上述这俩功能不是太紧急的话，我可以看看 【支持查询服务监听列表】这个 TODO 项。

**Comment by heqingpan** [comment]
tag主要用于多套开发环境对配置的隔离，命中tag则取tag对应的内容，否则取主干内容。

beta用于灰度发布，只对部分服务更新配置信息，再观察结果。避免出问题时整个系统不可用。合适大流量，服务器多，关键链路配置更新时使用。

上面的功能也可以通过其它方式实现。

-----

你选那TODO项做是没问题的。

**Comment by heqingpan** [comment]
感谢之前的共建投入，每个人的时间、精力、状态都会有变化，这个我也是能理解的。

后面有兴趣的话随时欢迎回来。

总之感谢:-)
