### ISSUE TITLE
想先了解下该项目重写的方式

### ISSUE THREAD

**Issue by leopardrota** [heqingpan/rnacos#33]
想问下老师，您用rust重写nacos server的方式，是以java语言的方式编写rust来重写，还是以rust语言本身的习惯来重写的，还是其他什么方式？

**Comment by heqingpan** [comment]
总体来说是以rust方式来写。

rust语言约束比java多，如所有权、生命周期等。如果想按照原java方式写很难走得通。

**Comment by leopardrota** [comment]
谢谢回复！支持以rust自己的方式来写，不然只会限制了rust该有的能力，开发也别扭。
