### ISSUE TITLE
期望日常测试中加入 nacos-sdk-rust 客户端

### ISSUE THREAD

**Issue by CherishCai** [heqingpan/rnacos#36]
有优化的地方也可以一同发现和升级 ～
relate https://github.com/nacos-group/nacos-sdk-rust/issues/208

**Comment by heqingpan** [comment]
好的，后会加上这部分的兼容。

**Comment by heqingpan** [comment]
对nacos-sdk-rust的兼容已经完成，本地使用nacos-sdk-rust/examples/simple_app.rs 已自测通过， r-nacos下个版本就会支持nacos-sdk-rust。

主要不兼容的点如下:
1. 查询时原r-nacos 返回的ConfigResponse.content_type为None，nacos-sdk-rust直接unwrap报错；r-nacos最新更新为都返回默认值 `Some("text".to_owned())`；
2.  监听通知请求ConfigChangeNotifyRequest,ConfigChangeNotifyRequest字段 headers,nacos-sdk-rust 默认不能为 None ；昨天r-nacos 为了兼容`nacos-sdk-go`已经把 headers 统一改成`headers: Option<HashMap<String, String>>` ,今天把监听通知请求改回`headers: HashMap<String, String>` ；


调整完上面两点后就可以兼容。
其实 v0.4.0应该已兼容第2点，第2点是为了兼容`nacos-sdk-go`引入的。

**Comment by CherishCai** [comment]
高效 666 @heqingpan

**Comment by heqingpan** [comment]
我把对主流sdk不兼容的问题当做r-nacos的 bug，对bug的修复优先级会排的比较高，尽力快速处理。

处理耗时短主要是不兼容的点不多，不兼容的方式也在预期范围内。
测试一遍基本就定位的原因，原因定位后改起来还是比较快的。

我后面发新版前会加入nacos-sdk-rust 客户端测试，也期望你们后面发新版前也把 r-nacos加入测试 :-)
