### ISSUE TITLE
Task Track: 支持查询服务监听列表

### ISSUE THREAD

**Issue by azusachino** [heqingpan/rnacos#7]
TODOs:

- [x] actix-web 中 actor 的相关内容，以及是如何使用的
- [-] 看一看 nacos 源码，熟悉这块对应的内容如何实现的 【逻辑实现不太一致】
- [/] 着手实现 config 这边对应的接口
- [x] 本地自测、提交PR

**Comment by azusachino** [comment]
理解错误，感觉是一个大坑。。nacos 本身提供的功能都有点看不太明白。😥

**Comment by heqingpan** [comment]
rnacos和nacos功能api是兼容的，不过实现上还是有些差别。

查询服务监听列表，可以把rnacos naming中注册的监听信息按条件取出，提供一个接口给控制台页面查询即可。
控制台页面接口不要求和nacos兼容。

**Comment by heqingpan** [comment]
接口完成后，我再抽空写对应控制台的前端页面。

如果前端页面你想要写也是可以的。

**Comment by azusachino** [comment]
> 查询服务监听列表，可以把rnacos naming中注册的监听信息按条件取出，提供一个接口给控制台页面查询即可。
控制台页面接口不要求和nacos兼容。

好的，这个跟我理解的是一致的。
差点以为是，config subscriber 那部分内容了，看了点 nacos 源码，真复杂。。
前端我也可以弄，vue3 是吧，刚好练练手了，vue2/3 差距还蛮大的。

**Comment by azusachino** [comment]
我想最终确认一下，需要实现的是【订阅者列表】这块的功能吧。
这个任务项放在了配置管理的下面，总让我以为是和配置相关的。。。
![image](https://github.com/heqingpan/rnacos/assets/18746830/7058f98a-5b47-45bb-935d-cc37a85d7743)

**Comment by heqingpan** [comment]
<img width="780" alt="image" src="https://github.com/heqingpan/rnacos/assets/1174480/4667e2d7-8810-4ea2-ae82-a777a28aacd2">

<img width="570" alt="image" src="https://github.com/heqingpan/rnacos/assets/1174480/0eec4e80-b7eb-4863-8bbd-f5e60c6c5927">

配置管理、服务管理下面都有一个监听或订阅列表。

**Comment by azusachino** [comment]
Config 这边看了蛮久的代码，没太看明白；刚刚去看了一下架构图，才大概了解 Listener 和 Subscriber 各自的用途。😥，太菜了。
Subscriber::listener 这边存储的就是 订阅了 当前 ConfigKey 的 client_id，也就是类似于 nacos 监听查询时的 IP 信息吧，作为一种标识符。所以，我这边只要把查询功能写成接口提供出来，就可以了吧。
ConfigListener::listner 这边是 http 长连接，timeout 去触发 sender 逻辑，感觉没看明白，这个有什么作用。。。🙃，就是这个逻辑把我困了很久。

actix-web，我没怎么用过，得花时间好好看一下，现在添加了一个 api，请求的时候总是返回 400 content type error，也不知道是怎么回事，调整 content-type 也没有用。🥲
另外，web 项目是不是也开一下 contributor 权限，方便后面提交内容啊。🙏

**Comment by heqingpan** [comment]
1. 监听查询的理解基本没问题
2. http长链接监听的机制：一次请求只收一次响应，每个请求有一个超时时间（30秒），在超时前如果监听的配置有变化，提前返回变化key信息。之后客户端再发一个新的长链接继续监听，循环上面的流程。
3. 错误的api和请求信息可以提供一下，我们一起看看。
4. 晚上给你加web项目权限。

**Comment by heqingpan** [comment]
0.3.x版本支持集群后，原查询服务监听列表的功能可能需要重新适配集群数据。
这个 issue 先关闭。
