### ISSUE TITLE
0.5.8添加配置会直接添加到public内

### ISSUE THREAD

**Issue by Clownsw** [heqingpan/rnacos#82]
刚刚尝试了一下`0.5.8`版本, 发现存在 在`a`命名空间内添加配置会添加到`public`中

**Comment by heqingpan** [comment]
收到，0.5.8的前端使用大重构后的控制台版本，应该是新控制台前端引入的问题。

这两天我抽空处理下再发一个新版本出来。

可以暂时先回切到0.5.7操作。

**Comment by heqingpan** [comment]
v0.5.9版本已修复
