### ISSUE TITLE
你好, 不支持/nacos/v1/auth/users/login这个接口吗

### ISSUE THREAD

**Issue by Clownsw** [heqingpan/rnacos#83]
```bash
c.a.n.c.a.i.process.HttpLoginProcessor   : [NacosClientAuthServiceImpl] login http request failed url: http://127.0.0.1:8848/nacos/v1/auth/users/login, params: {username=base}, bodyMap: {password=base}, errorMsg: Read timed out
```

直接访问该接口 `HTTP ERROR 405`

请问是否目前不支持该接口?

**Comment by heqingpan** [comment]
应该是支持的，你使用的是哪个版本？

如果是使用刚发布的0.5.8版本，那么可以切换到0.5.7试试。

我晚点也自己测试看看。

**Comment by heqingpan** [comment]
如果方便的话可以提供一下r-nacos的版本号与当时的日志。

**Comment by heqingpan** [comment]
是的，正常来说应该没有问题，至少不会是超时。

你那边可以稳定复现吗？

我回去也用对应的客户端版本验证看看。

**Comment by heqingpan** [comment]
收到，能复现应该就好处理。

晚上回去试试能否复现。

**Comment by heqingpan** [comment]
在0.5.7版本之前是的，在0.5.8之后支持通过配置RNACOS_ENABLE_OPEN_API_AUTH开启接口鉴权。

**Comment by heqingpan** [comment]
> > 收到，能复现应该就好处理。
> > 晚上回去试试能否复现。
> 
> 似乎是 `RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT`的问题, 默认是 `5`, 正好第6次请求登录接口直接卡住, 我把它改成 `100`就没问题了

我这没能复现,环境: r-nacos v0.5.7, nacos-client 2.2.4，jdk 1.8, MacOS。 
看起来可能是和不同的环境有关。

看起来你是用r-nacos v0.5.8就没有问题。
如果是这样的话，可能和v0.5.7与0.5.8返回格式不同的点也有关。v0.5.7直接返回字符串转`Responder`，v0.5.8是返回HttpResponse对象。

对于r-nacos v0.5.7 和你的超时问题,你可以试试打包出jar后单独运行，不要在idea中直接运行。
我之前有遇到过idea运行http请求接口超时，而其它方式请求http接口是正常的经历

如果v0.5.8之后就没有问题，那么这个问题总的来说也算在新版解决了是吗？

**Comment by heqingpan** [comment]
你出问题时都是通过idea运行的吗？

有试过build jar出来单独运行做对比吗？

我这边目前暂时复现不出来。

如果你build出来验证还有问题的话，把问题场景单独抽出提供一个demo工程吗？这样我就可以用demo工程尝试复现。

**Comment by heqingpan** [comment]
你出问题时都是通过idea运行的吗？

有试过build jar出来单独运行做对比吗？

我这边目前暂时复现不出来。

如果你build出来验证还有问题的话，把问题场景单独抽出提供一个demo工程吗？这样我就可以用demo工程尝试复现。

**Comment by heqingpan** [comment]
好的
