### ISSUE TITLE
疑似资源不释放, 导致内存只涨不降

### ISSUE THREAD

**Issue by Clownsw** [heqingpan/rnacos#94]
r-nacos: v0.5.9
两个程序(两个配置), 二十个服务左右
反复注册(开发需要来回重启服务, 有个几十次), 从最开始6mb左右到12mb, 中间即使停止服务内存也不会释放
疑似有资源泄露未释放

![image](https://github.com/nacos-group/r-nacos/assets/28394742/c96cdf2e-b81d-474d-b78d-75ccb9227c57)

**Comment by heqingpan** [comment]
之前的版本做过连续压测，压测停止后上涨的内存不会完全降到启动前水平，但也是会降到一个稳定水位。当时观察下来，这种不是无限增长，应该不是内存泄露。

这个版本我没有专门测过。

你可以把时间拉长，应用多更新多次，看看内存是不是每次都增长。如果不是每次都增长那应该就没这个问题。

**Comment by heqingpan** [comment]
我后面抽空也测试验证一下。

另外docker的内存计数与在系统中直接运行的内容计数有一些差异。

我之前的压测内存数据是直接在系统运行的。

**Comment by heqingpan** [comment]
我想起一个差异点,v0.5.9开启鉴权后，鉴权的数据是放到缓存中，缓存过期时间是1个小时。也就是如果开启鉴权，需要等一小时后再观察内存。

后面考虑支持通过jwt鉴权。

**Comment by heqingpan** [comment]
目前缓存只有在操作时尝试清除过期数据，没有加定时清理兜底。

正常使用过程至少每一个小时触发清理一次过期数据，这样就不会有一直没被清理的数据，缓存内存会保存在一定水位。

我这几天手头没电脑，后面我再加上定时间隔的兜底清理策略，应该就能避免这个现象。

**Comment by heqingpan** [comment]
收到，这个我过两天回家之后再看看。

你有用v0.5.7做相同的操作对比过吗？
想确认是不是这两个版本引入的问题。

没有的话我回去再做对比好了

**Comment by heqingpan** [comment]
那可能就不是这个原因了。

我回去之后再看看。

**Comment by heqingpan** [comment]
对了，你是用什么客户端版本？

**Comment by heqingpan** [comment]
周末outing回来太晚来不及复现确认，这几天我再抽空复现确认问题。

**Comment by heqingpan** [comment]
已确认存在这个问题，并通过批量链接工具可以稳定复现问题。

初步确认和grpc长链接关闭后对应的资源没能自动释放有关，后面几天会优先处理这个 bug。

每个链接占用的内存都不大，内存会缓慢增加，一般场景运行几天可能变化不明显。

正在使用的用户，如果发现问题可以通过重启临时解决，也可以设置定时重启（每天重启一次即可）。

**Comment by heqingpan** [comment]
对r-nacos做多批次重联测试，发起前几次内存增长比较明显，后面内存收敛趋于稳定，基本不增长。

最新的结论为： grpc重复链接不会导致内存无限增长。

测试版本：v0.5.10，操作系统：MacOS x86 ， 每批次并发100个链接。
测试结果如下：


| 专用内存(M) | 实际内存(M) | 重联批次 |
| ---- | ---- | ---- |
| 5.9 | 10.8 | 0 |
| 9.4 | 15.4 | 1 |
| 10.8 | 16.8 | 2 |
| 12.2 | 18.1 | 3 |
| 13.0 | 19.0 | 4 |
| 13.5 | 19.5 | 5 |
| 13.9 | 19.8 | 6 |
| 14.1 | 20.0 | 7 |
| 14.4 | 20.3 | 8 |
| 14.4 | 20.4 | 9 |
| 14.5 | 20.4 | 10 |
| 15.3 | 19.0 | 11 |
| 15.5 | 19.1 | 12 |
| 15.8 | 19.5 | 13 |
| 16.0 | 19.7 | 14 |
| 16.0 | 19.7 | 15 |
| 16.0 | 19.7 | 16 |
| 16.0 | 19.8 | 17 |
| 16.1 | 19.8 | 18 |
| 16.2 | 19.8 | 19 |
| 16.2 | 19.9 | 20 |
| 16.3 | 19.9 | 21 |
| 16.3 | 19.9 | 22 |
| 16.3 | 19.9 | 23 |


![image](https://github.com/nacos-group/r-nacos/assets/1174480/70180c52-9d2e-41e2-be1c-b09331a31c24)


---

同时在本地对验证微调后的版本做同样的测试，测试结果如下：


| 专用内存(M) | 实际内存(M) | 重联批次 |
| ---- | ---- | ---- |
| 5.9 | 10.7 | 0 |
| 10.1 | 16.0 | 1 |
| 11.9 | 17.9 | 2 |
| 13 | 19 | 3 |
| 13.5 | 19.5 | 4 |
| 14.2 | 20.2 | 5 |
| 14.9 | 20.8 | 6 |
| 14.9 | 20.9 | 7 |
| 15.2 | 21.2 | 8 |
| 15.3 | 21.3 | 9 |
| 15.3 | 21.3 | 10 |
| 15.4 | 21.4 | 11 |
| 15.4 | 21.4 | 12 |
| 15.4 | 21.4 | 13 |

![image](https://github.com/nacos-group/r-nacos/assets/1174480/ddbf036d-8c85-4b40-9e93-d65aa49d463c)

**Comment by heqingpan** [comment]
从测试结果可以推测：
r-nacos应用运行过程中，部分集合（HashMap,Vec 等）会因数据量增加而自动扩容（占用的内存变大），而元素移除时不会自动缩容，集合内存保持给后继的数据使用。 

当集合容量到大一定量级时，基本足够业务数据的循环使用，这时容量基本也就不需要再扩容，内存趋于稳定。

**Comment by heqingpan** [comment]
这里是想说明切换到mimalloc后内存稳定水位更低吗？

关于提换底层的内存分配器影响面比较大，需要通过充分测试比较之后才好确定是否应该切换。

**Comment by heqingpan** [comment]
收到，我后面有空时会试试，不过时间上应该会晚一点。
